name: Ping Guild Every 5 Minutes

on:
  schedule:
    - cron: '*/20 * * * *' 
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    environment: hidden 

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          PING_USER_ID: ${{ secrets.PING_USER_ID }}
          GUILD_NAME: ${{ secrets.GUILD_NAME }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          GUILD_RANK: ${{ secrets.GUILD_RANK }}
          LEVEL_THRESHOLD: ${{ secrets.LEVEL_THRESHOLD }}
        run: node index.js
