name: Run Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: 

jobs:
  cron-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.7'

      - name: Run task
        env:
          env: ${{ secrets.env }}
        run: |
          node index.js
